name: Build and Release NuGet Package (.NET Framework 4.8.1)

on:
  workflow_call:
    inputs:
      runner_label:
        type: string
        required: false
        default: 'windows-latest'
      artifact_name:
        type: string
        required: false
      artifact_path:
        type: string
        required: false
        
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner_label }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conditionally download artifact
        if: ${{ inputs.artifact_name && inputs.artifact_path }}
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}

      - name: List contents of a specific folder (Windows)
        shell: powershell
        run: |
          $targetFolder =  ${{ inputs.artifact_path }}
          
          if (Test-Path $targetFolder) {
            Write-Host "--- Listing contents of '$targetFolder' ---"
            Get-ChildItem -Path $targetFolder
          } else {
            Write-Host "--- Folder '$targetFolder' not found. ---"
          }
